######################################################################
##
## dream-ant axboot Flyway 스크립트
##
######################################################################

## [테이블 생성]
## 01. auth_group_map
## 02. child_sample
## 03. common_code
## 04. error_log
## 05. file
## 06. menu
## 07. parent_sample
## 08. program
## 09. user
## 10. user_auth
## 11. user_role

# ___ auth_group_map ___

CREATE TABLE `auth_group_map` (
  `GRP_AUTH_CD` VARCHAR(100) NOT NULL,
  `MENU_ID` BIGINT(20) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `DEL_AH` VARCHAR(1) NULL DEFAULT NULL,
  `EXL_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN1_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN2_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN3_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN4_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN5_AH` VARCHAR(1) NULL DEFAULT NULL,
  `SAV_AH` VARCHAR(1) NULL DEFAULT NULL,
  `SCH_AH` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`GRP_AUTH_CD`, `MENU_ID`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;

# ___ child_sample ___
CREATE TABLE `child_sample` (
  `SAMPLE_KEY` VARCHAR(255) NOT NULL,
  `ETC1` VARCHAR(255) NULL DEFAULT NULL,
  `ETC2` VARCHAR(255) NULL DEFAULT NULL,
  `ETC3` VARCHAR(255) NULL DEFAULT NULL,
  `SAMPLE_PARENT_KEY` VARCHAR(255) NULL DEFAULT NULL,
  `SAMPLE_VALUE` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`SAMPLE_KEY`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;

# ___ common_code ___
CREATE TABLE `common_code` (
  `CODE` VARCHAR(100) NOT NULL,
  `GROUP_CD` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `DATA1` VARCHAR(100) NULL DEFAULT NULL,
  `DATA2` VARCHAR(100) NULL DEFAULT NULL,
  `DATA3` VARCHAR(100) NULL DEFAULT NULL,
  `DATA4` INT(11) NULL DEFAULT NULL,
  `DATA5` INT(11) NULL DEFAULT NULL,
  `GROUP_NM` VARCHAR(100) NULL DEFAULT NULL,
  `NAME` VARCHAR(50) NULL DEFAULT NULL,
  `REMARK` VARCHAR(200) NULL DEFAULT NULL,
  `SORT` INT(11) NULL DEFAULT NULL,
  `USE_YN` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`CODE`, `GROUP_CD`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;

# ___ error_log ___
CREATE TABLE `error_log` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ALERT_YN` VARCHAR(1) NULL DEFAULT NULL,
  `ERROR_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `HEADER_MAP` TEXT NULL,
  `HOST_NAME` VARCHAR(50) NULL DEFAULT NULL,
  `LOGGER_NAME` VARCHAR(300) NULL DEFAULT NULL,
  `MESSAGE` TEXT NULL,
  `PARAMETER_MAP` TEXT NULL,
  `PATH` VARCHAR(2048) NULL DEFAULT NULL,
  `PHASE` VARCHAR(10) NULL DEFAULT NULL,
  `SERVER_NAME` VARCHAR(50) NULL DEFAULT NULL,
  `SYSTEM` VARCHAR(50) NULL DEFAULT NULL,
  `TRACE` TEXT NULL,
  `USER_INFO` TEXT NULL,
  PRIMARY KEY (`ID`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;

# ___ file ___
CREATE TABLE `file` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `DEL_YN` VARCHAR(1) NULL DEFAULT NULL,
  `FILE_DESC` TEXT NULL,
  `EXTENSION` VARCHAR(10) NULL DEFAULT NULL,
  `FILE_NM` TEXT NULL,
  `FILE_SIZE` BIGINT(20) NULL DEFAULT NULL,
  `FILE_TYPE` VARCHAR(30) NULL DEFAULT NULL,
  `SAVE_NM` TEXT NULL,
  `SORT` INT(11) NULL DEFAULT NULL,
  `TARGET_ID` VARCHAR(100) NULL DEFAULT NULL,
  `TARGET_TYPE` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
  AUTO_INCREMENT=30
;

# ___ menu ___
CREATE TABLE `menu` (
  `MENU_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `LEVEL` INT(11) NULL DEFAULT NULL,
  `MENU_GRP_CD` VARCHAR(100) NULL DEFAULT NULL,
  `MENU_NM` VARCHAR(100) NULL DEFAULT NULL,
  `PARENT_ID` BIGINT(20) NULL DEFAULT NULL,
  `PROG_CD` VARCHAR(50) NULL DEFAULT NULL,
  `SORT` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`MENU_ID`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;

# ___ parent_sample ___
CREATE TABLE `parent_sample` (
  `SAMPLE_KEY` VARCHAR(255) NOT NULL,
  `ETC1` VARCHAR(255) NULL DEFAULT NULL,
  `ETC2` VARCHAR(255) NULL DEFAULT NULL,
  `ETC3` VARCHAR(255) NULL DEFAULT NULL,
  `ETC4` VARCHAR(255) NULL DEFAULT NULL,
  `SAMPLE_VALUE` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`SAMPLE_KEY`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;

# ___ program ___
CREATE TABLE `program` (
  `PROG_CD` VARCHAR(50) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `AUTH_CHECK` VARCHAR(1) NULL DEFAULT NULL,
  `DEL_AH` VARCHAR(1) NULL DEFAULT NULL,
  `EXL_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN1_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN2_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN3_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN4_AH` VARCHAR(1) NULL DEFAULT NULL,
  `FN5_AH` VARCHAR(1) NULL DEFAULT NULL,
  `PROG_NM` VARCHAR(50) NULL DEFAULT NULL,
  `PROG_PH` VARCHAR(100) NULL DEFAULT NULL,
  `REMARK` VARCHAR(200) NULL DEFAULT NULL,
  `SAV_AH` VARCHAR(1) NULL DEFAULT NULL,
  `SCH_AH` VARCHAR(1) NULL DEFAULT NULL,
  `TARGET` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`PROG_CD`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;

# ___ user ___
CREATE TABLE `user` (
  `USER_CD` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `DEL_YN` VARCHAR(1) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `HP_NO` VARCHAR(15) NULL DEFAULT NULL,
  `IP` VARCHAR(100) NULL DEFAULT NULL,
  `LAST_LOGIN_DATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LOCALE` VARCHAR(10) NULL DEFAULT NULL,
  `MENU_GRP_CD` VARCHAR(100) NULL DEFAULT NULL,
  `PASSWORD_UPDATE_DATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `REMARK` VARCHAR(200) NULL DEFAULT NULL,
  `USE_YN` VARCHAR(1) NOT NULL,
  `USER_NM` VARCHAR(30) NOT NULL,
  `USER_PS` VARCHAR(128) NOT NULL,
  `USER_STATUS` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`USER_CD`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;

# ___ user_auth ___
CREATE TABLE `user_auth` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `GRP_AUTH_CD` VARCHAR(255) NULL DEFAULT NULL,
  `USER_CD` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;

# ___ user_role ___
CREATE TABLE `user_role` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_BY` VARCHAR(255) NULL DEFAULT NULL,
  `ROLE_CD` VARCHAR(100) NOT NULL,
  `USER_CD` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;
